service: tongue-bender

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-2
  environment:
    TELEGRAM_TOKEN: ${ssm:telegram_key}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'sqs:SendMessage'
        - 'sqs:GetQueueUrl'
      Resource: 'arn:aws:sqs:eu-west-2:035313854880:task'
    - Effect: 'Allow'
      Action:
        - 'sqs:ListQueues'
      Resource: 'arn:aws:sqs:eu-west-2:035313854880:task:*'
    - Effect: 'Allow'
      Action:
        - 'sqs:SendMessage'
        - 'sqs:GetQueueUrl'
      Resource: 'arn:aws:sqs:eu-west-2:035313854880:msg'
    - Effect: 'Allow'
      Action:
        - 'sqs:ListQueues'
      Resource: 'arn:aws:sqs:eu-west-2:035313854880:msg:*'

functions:
  telegramHook:
    handler: handler.telegramHook
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

  sqsTrigger:
    handler: handler.sqsTrigger
    events:
      - sqs: arn:aws:sqs:eu-west-2:035313854880:msg
